//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.06.25 at 12:10:34 PM CST 
//


package com.ibm.xmlns.prod.websphere.wbiserver.map._6_0;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.namespace.QName;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="inputBusinessObjectVariable"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                 &lt;attribute name="businessObjectRef" type="{http://www.w3.org/2001/XMLSchema}QName" /&gt;
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="outputBusinessObjectVariable"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                 &lt;attribute name="businessObjectRef" type="{http://www.w3.org/2001/XMLSchema}QName" /&gt;
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="propertyMap" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="custom"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="input"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;simpleContent&gt;
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                                     &lt;attribute name="businessObjectVariableRef" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                     &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                   &lt;/extension&gt;
 *                                 &lt;/simpleContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="output"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;simpleContent&gt;
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                                     &lt;attribute name="businessObjectVariableRef" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                     &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                   &lt;/extension&gt;
 *                                 &lt;/simpleContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="javaCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="executionOrder" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="targetNamespace" type="{http://www.w3.org/2001/XMLSchema}anyURI" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "inputBusinessObjectVariable",
    "outputBusinessObjectVariable",
    "propertyMaps"
})
@XmlRootElement(name = "businessObjectMap")
public class BusinessObjectMap
    implements Serializable
{

    private final static long serialVersionUID = -1L;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected BusinessObjectMap.InputBusinessObjectVariable inputBusinessObjectVariable;
    @XmlElement(required = true)
    protected BusinessObjectMap.OutputBusinessObjectVariable outputBusinessObjectVariable;
    @XmlElement(name = "propertyMap")
    protected List<BusinessObjectMap.PropertyMap> propertyMaps;
    @XmlAttribute(name = "targetNamespace")
    @XmlSchemaType(name = "anyURI")
    protected String targetNamespace;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the inputBusinessObjectVariable property.
     * 
     * @return
     *     possible object is
     *     {@link BusinessObjectMap.InputBusinessObjectVariable }
     *     
     */
    public BusinessObjectMap.InputBusinessObjectVariable getInputBusinessObjectVariable() {
        return inputBusinessObjectVariable;
    }

    /**
     * Sets the value of the inputBusinessObjectVariable property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusinessObjectMap.InputBusinessObjectVariable }
     *     
     */
    public void setInputBusinessObjectVariable(BusinessObjectMap.InputBusinessObjectVariable value) {
        this.inputBusinessObjectVariable = value;
    }

    /**
     * Gets the value of the outputBusinessObjectVariable property.
     * 
     * @return
     *     possible object is
     *     {@link BusinessObjectMap.OutputBusinessObjectVariable }
     *     
     */
    public BusinessObjectMap.OutputBusinessObjectVariable getOutputBusinessObjectVariable() {
        return outputBusinessObjectVariable;
    }

    /**
     * Sets the value of the outputBusinessObjectVariable property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusinessObjectMap.OutputBusinessObjectVariable }
     *     
     */
    public void setOutputBusinessObjectVariable(BusinessObjectMap.OutputBusinessObjectVariable value) {
        this.outputBusinessObjectVariable = value;
    }

    /**
     * Gets the value of the propertyMaps property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the propertyMaps property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPropertyMaps().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BusinessObjectMap.PropertyMap }
     * 
     * 
     */
    public List<BusinessObjectMap.PropertyMap> getPropertyMaps() {
        if (propertyMaps == null) {
            propertyMaps = new ArrayList<BusinessObjectMap.PropertyMap>();
        }
        return this.propertyMaps;
    }

    /**
     * Gets the value of the targetNamespace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetNamespace() {
        return targetNamespace;
    }

    /**
     * Sets the value of the targetNamespace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetNamespace(String value) {
        this.targetNamespace = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;simpleContent&gt;
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *       &lt;attribute name="businessObjectRef" type="{http://www.w3.org/2001/XMLSchema}QName" /&gt;
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *     &lt;/extension&gt;
     *   &lt;/simpleContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class InputBusinessObjectVariable
        implements Serializable
    {

        private final static long serialVersionUID = -1L;
        @XmlValue
        protected String value;
        @XmlAttribute(name = "businessObjectRef")
        protected QName businessObjectRef;
        @XmlAttribute(name = "name")
        protected String name;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the businessObjectRef property.
         * 
         * @return
         *     possible object is
         *     {@link QName }
         *     
         */
        public QName getBusinessObjectRef() {
            return businessObjectRef;
        }

        /**
         * Sets the value of the businessObjectRef property.
         * 
         * @param value
         *     allowed object is
         *     {@link QName }
         *     
         */
        public void setBusinessObjectRef(QName value) {
            this.businessObjectRef = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;simpleContent&gt;
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *       &lt;attribute name="businessObjectRef" type="{http://www.w3.org/2001/XMLSchema}QName" /&gt;
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *     &lt;/extension&gt;
     *   &lt;/simpleContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class OutputBusinessObjectVariable
        implements Serializable
    {

        private final static long serialVersionUID = -1L;
        @XmlValue
        protected String value;
        @XmlAttribute(name = "businessObjectRef")
        protected QName businessObjectRef;
        @XmlAttribute(name = "name")
        protected String name;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the businessObjectRef property.
         * 
         * @return
         *     possible object is
         *     {@link QName }
         *     
         */
        public QName getBusinessObjectRef() {
            return businessObjectRef;
        }

        /**
         * Sets the value of the businessObjectRef property.
         * 
         * @param value
         *     allowed object is
         *     {@link QName }
         *     
         */
        public void setBusinessObjectRef(QName value) {
            this.businessObjectRef = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="custom"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="input"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;simpleContent&gt;
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *                           &lt;attribute name="businessObjectVariableRef" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                           &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                         &lt;/extension&gt;
     *                       &lt;/simpleContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="output"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;simpleContent&gt;
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *                           &lt;attribute name="businessObjectVariableRef" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                           &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                         &lt;/extension&gt;
     *                       &lt;/simpleContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="javaCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="executionOrder" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "custom"
    })
    public static class PropertyMap
        implements Serializable
    {

        private final static long serialVersionUID = -1L;
        @XmlElement(required = true)
        protected BusinessObjectMap.PropertyMap.Custom custom;
        @XmlAttribute(name = "executionOrder")
        protected Byte executionOrder;

        /**
         * Gets the value of the custom property.
         * 
         * @return
         *     possible object is
         *     {@link BusinessObjectMap.PropertyMap.Custom }
         *     
         */
        public BusinessObjectMap.PropertyMap.Custom getCustom() {
            return custom;
        }

        /**
         * Sets the value of the custom property.
         * 
         * @param value
         *     allowed object is
         *     {@link BusinessObjectMap.PropertyMap.Custom }
         *     
         */
        public void setCustom(BusinessObjectMap.PropertyMap.Custom value) {
            this.custom = value;
        }

        /**
         * Gets the value of the executionOrder property.
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Byte getExecutionOrder() {
            return executionOrder;
        }

        /**
         * Sets the value of the executionOrder property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         */
        public void setExecutionOrder(Byte value) {
            this.executionOrder = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="input"&gt;
         *           &lt;complexType&gt;
         *             &lt;simpleContent&gt;
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
         *                 &lt;attribute name="businessObjectVariableRef" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                 &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *               &lt;/extension&gt;
         *             &lt;/simpleContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="output"&gt;
         *           &lt;complexType&gt;
         *             &lt;simpleContent&gt;
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
         *                 &lt;attribute name="businessObjectVariableRef" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                 &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *               &lt;/extension&gt;
         *             &lt;/simpleContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="javaCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "input",
            "output",
            "javaCode"
        })
        public static class Custom
            implements Serializable
        {

            private final static long serialVersionUID = -1L;
            @XmlElement(required = true)
            protected BusinessObjectMap.PropertyMap.Custom.Input input;
            @XmlElement(required = true)
            protected BusinessObjectMap.PropertyMap.Custom.Output output;
            @XmlElement(required = true)
            protected String javaCode;

            /**
             * Gets the value of the input property.
             * 
             * @return
             *     possible object is
             *     {@link BusinessObjectMap.PropertyMap.Custom.Input }
             *     
             */
            public BusinessObjectMap.PropertyMap.Custom.Input getInput() {
                return input;
            }

            /**
             * Sets the value of the input property.
             * 
             * @param value
             *     allowed object is
             *     {@link BusinessObjectMap.PropertyMap.Custom.Input }
             *     
             */
            public void setInput(BusinessObjectMap.PropertyMap.Custom.Input value) {
                this.input = value;
            }

            /**
             * Gets the value of the output property.
             * 
             * @return
             *     possible object is
             *     {@link BusinessObjectMap.PropertyMap.Custom.Output }
             *     
             */
            public BusinessObjectMap.PropertyMap.Custom.Output getOutput() {
                return output;
            }

            /**
             * Sets the value of the output property.
             * 
             * @param value
             *     allowed object is
             *     {@link BusinessObjectMap.PropertyMap.Custom.Output }
             *     
             */
            public void setOutput(BusinessObjectMap.PropertyMap.Custom.Output value) {
                this.output = value;
            }

            /**
             * Gets the value of the javaCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getJavaCode() {
                return javaCode;
            }

            /**
             * Sets the value of the javaCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setJavaCode(String value) {
                this.javaCode = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;simpleContent&gt;
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
             *       &lt;attribute name="businessObjectVariableRef" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *       &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *     &lt;/extension&gt;
             *   &lt;/simpleContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class Input
                implements Serializable
            {

                private final static long serialVersionUID = -1L;
                @XmlValue
                protected String value;
                @XmlAttribute(name = "businessObjectVariableRef")
                protected String businessObjectVariableRef;
                @XmlAttribute(name = "property")
                protected String property;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the businessObjectVariableRef property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getBusinessObjectVariableRef() {
                    return businessObjectVariableRef;
                }

                /**
                 * Sets the value of the businessObjectVariableRef property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setBusinessObjectVariableRef(String value) {
                    this.businessObjectVariableRef = value;
                }

                /**
                 * Gets the value of the property property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getProperty() {
                    return property;
                }

                /**
                 * Sets the value of the property property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setProperty(String value) {
                    this.property = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;simpleContent&gt;
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
             *       &lt;attribute name="businessObjectVariableRef" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *       &lt;attribute name="property" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *     &lt;/extension&gt;
             *   &lt;/simpleContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class Output
                implements Serializable
            {

                private final static long serialVersionUID = -1L;
                @XmlValue
                protected String value;
                @XmlAttribute(name = "businessObjectVariableRef")
                protected String businessObjectVariableRef;
                @XmlAttribute(name = "property")
                protected String property;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the businessObjectVariableRef property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getBusinessObjectVariableRef() {
                    return businessObjectVariableRef;
                }

                /**
                 * Sets the value of the businessObjectVariableRef property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setBusinessObjectVariableRef(String value) {
                    this.businessObjectVariableRef = value;
                }

                /**
                 * Gets the value of the property property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getProperty() {
                    return property;
                }

                /**
                 * Sets the value of the property property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setProperty(String value) {
                    this.property = value;
                }

            }

        }

    }

}
