//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.06.25 at 12:10:34 PM CST 
//


package com.ibm.xmlns.prod.websphere.wbiserver.map._6_0;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ibm.xmlns.prod.websphere.wbiserver.map._6_0 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ibm.xmlns.prod.websphere.wbiserver.map._6_0
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BusinessObjectMap }
     * 
     */
    public BusinessObjectMap createBusinessObjectMap() {
        return new BusinessObjectMap();
    }

    /**
     * Create an instance of {@link BusinessObjectMap.PropertyMap }
     * 
     */
    public BusinessObjectMap.PropertyMap createBusinessObjectMapPropertyMap() {
        return new BusinessObjectMap.PropertyMap();
    }

    /**
     * Create an instance of {@link BusinessObjectMap.PropertyMap.Custom }
     * 
     */
    public BusinessObjectMap.PropertyMap.Custom createBusinessObjectMapPropertyMapCustom() {
        return new BusinessObjectMap.PropertyMap.Custom();
    }

    /**
     * Create an instance of {@link BusinessObjectMap.InputBusinessObjectVariable }
     * 
     */
    public BusinessObjectMap.InputBusinessObjectVariable createBusinessObjectMapInputBusinessObjectVariable() {
        return new BusinessObjectMap.InputBusinessObjectVariable();
    }

    /**
     * Create an instance of {@link BusinessObjectMap.OutputBusinessObjectVariable }
     * 
     */
    public BusinessObjectMap.OutputBusinessObjectVariable createBusinessObjectMapOutputBusinessObjectVariable() {
        return new BusinessObjectMap.OutputBusinessObjectVariable();
    }

    /**
     * Create an instance of {@link BusinessObjectMap.PropertyMap.Custom.Input }
     * 
     */
    public BusinessObjectMap.PropertyMap.Custom.Input createBusinessObjectMapPropertyMapCustomInput() {
        return new BusinessObjectMap.PropertyMap.Custom.Input();
    }

    /**
     * Create an instance of {@link BusinessObjectMap.PropertyMap.Custom.Output }
     * 
     */
    public BusinessObjectMap.PropertyMap.Custom.Output createBusinessObjectMapPropertyMapCustomOutput() {
        return new BusinessObjectMap.PropertyMap.Custom.Output();
    }

}
