//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.06.25 at 12:10:34 PM CST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.ibm.com/xmlns/prod/websphere/wbiserver/map/6.0.0", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ibm.xmlns.prod.websphere.wbiserver.map._6_0;
